# Generated by Django 3.1.2 on 2020-10-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default=0, upload_to='pics/thumbnails'),
            preserve_default=False,
        ),
    ]
